# Time series decomposition
TODO - Placeholder: https://otexts.com/fpp2/decomposition.html - https://www.tigerdata.com/blog/time-series-introduction#what-is-time-series-data-and-how-to-use-it

Time series data often exhibit patterns such as trends, seasonality, and cycles.
Decomposing a time series into its components can help to better understand the underlying processes.

Time series are usually decomposed into three components:
- **Trend**: $T_t$, long-term progression of the series (e.g., increasing or decreasing).
- **Seasonality**: $S_t$, regular patterns that repeat over a fixed period (e.g., daily, weekly, yearly).
- **Residual**: $I_t$, random noise or irregular component.

Additive models assume that the components add together to form the time series:
$$ Y_t = T_t + S_t + I_t $$

Multiplicative models assume that the components multiply together to form the time series:
$$ Y_t = T_t \times S_t \times I_t $$

:::{.callout-note}
Sometimes, also a fourth component, **Cyclic** ($C_t$), is considered, which represents long-term oscillations that are not of fixed period.
:::

## Examples

{{< embed /3_act3/2_2_timeseries_decomposition_example.ipynb echo=true >}}
