project:
  type: book

bibliography: references.bib
number-sections: true
number-parts: true
number-depth: 5
toc: true
toc-depth: 3

book: 
  author:
    - name: Gregor Ehrensperger
      orcid: 0000-0003-4816-0233
      corresponding: true
      email: g@ehrensperger.dev
      affiliations:
        - ehrensperger.dev
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
        - 0_introduction/0_introduction.qmd
        - 0_introduction/1_history.qmd
        - 0_introduction/2_applications.qmd
    - part: "Act 1: Polished Machine Data"
      chapters: 
        - act1/0_0_predictive_maintenance.qmd
        - act1/1_self_study_session1.qmd
        - act1/2_self_study_session2.qmd
        - act1/3_self_study_session3.qmd
        - act1/4_self_study_session4.qmd
    - part: "Act 2: Advanced Machine Data"
      chapters: 
        - act2/0_introduction.qmd
        - act2/1_levels_of_system_integration.qmd
        - act2/2_batch_vs_stream.qmd
    - part: "Act 3: Live stream"
      chapters: 
        - act3/0_index.qmd
    - 2_references.qmd
  date: last-modified
  license: "CC BY-NC-SA 4.0"
  page-footer:
    left: Industrial Data Science - 2025 - [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 
    center: "Gregor Ehrensperger"
    right: Manuscript designed with <a href="https://quarto.org/">Quarto</a>.
  reader-mode: true
  repo-actions: [edit, issue]
  repo-branch: main
  repo-url: https://github.com/noxthot/ws25_mci_industrial_ds_manuscript
  title: Industrial Data Science

format:
  html:
    comments:
      hypothesis: true
    page-layout: full
    theme:
      light: [simplex]
      dark: [superhero]
