project:
  type: book

bibliography: references.bib
number-sections: true
number-parts: true
number-depth: 5
toc: true
toc-depth: 3

book: 
  author:
    - name: Gregor Ehrensperger
      orcid: 0000-0003-4816-0233
      corresponding: true
      email: g@ehrensperger.dev
      affiliations:
        - ehrensperger.dev
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
        - 0_introduction/0_introduction.qmd
        - 0_introduction/1_history.qmd
        - 0_introduction/2_applications.qmd
    - part: "Act 1: Polished Machine Data"
      chapters: 
        - 1_act1/0_0_predictive_maintenance.qmd
        - 1_act1/1_self_study_session1.qmd
        - 1_act1/2_self_study_session2.qmd
        - 1_act1/3_self_study_session3.qmd
        - 1_act1/4_self_study_session4.qmd
    - part: "Act 2: Time series -- A Curated Collection"
      chapters: 
        - 2_act2/0_nature_of_timeseries.qmd
        - 2_act2/1_0_data_imputation.qmd
        - 2_act2/2_1_timeseries_decomposition.qmd
        - 2_act2/3_1_timeseries_clustering.qmd
        - 2_act2/4_1_timeseries_classification.qmd
        - 2_act2/5_timeseries_regression.qmd
        - 2_act2/x_self_study_session1.qmd
        - 2_act2/x_self_study_session2.qmd
    - part: "Act 3: Real Machine Data"
      chapters: 
        - 3_act3/0_challenges.qmd
        - 3_act3/1_levels_of_system_integration.qmd
        - 3_act3/2_batch_vs_stream.qmd
        - 3_act3/3_0_process_optimization_sensor_data.qmd
        - 3_act3/4_live_feedback.qmd
        - 3_act3/x_self_study_session1.qmd
        - 3_act3/x_self_study_session2.qmd
    - part: "Act 4: Lost Tapes"
      chapters: 
        - 4_act4/0_index.qmd
    - 5_references.qmd
  date: last-modified
  license: "CC BY-NC-SA 4.0"
  page-footer:
    left: Industrial Data Science - 2025 - [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 
    center: "Gregor Ehrensperger"
    right: Manuscript designed with <a href="https://quarto.org/">Quarto</a>.
  reader-mode: true
  repo-actions: [edit, issue]
  repo-branch: main
  repo-url: https://github.com/noxthot/ws25_mci_industrial_ds_manuscript
  title: Industrial Data Science

format:
  html:
    comments:
      hypothesis: true
    page-layout: full
    theme:
      light: [simplex]
      dark: [superhero]
