# Self study
This class contains self-study sessions to reinforce your understanding of the material and explore other aspects of the topic in a self-guided manner.

## Session 1
In this session, you will explore the dataset in @sec-act1 further.

When comparing our findings in @sec-act1-1-int-pp and @sec-act1-1-int-dt with the failure description in @sec-act1-1-reveal, we can see that we did a pretty good job in identifying failure reasons.
However, we could have done better for `OSF`.

::: {.callout-caution appearance="simple" collapse="true" icon=false}
:::: {#exr-basics-mv-space}
## Overstrain failure
::::
According to @sec-act1-1-reveal, the failure type _overstrain failure_ (`OSF`) occurs when the machine is subjected to excessive torque when a worn out tool is used.
Also the product variant is associated to the failure rate: When the product of torque and tool wear exceeds 11.000 minNm for the L product variant (12.000 for M, 13.000 for H), the process fails due to overstrain.

Are you able to verify this relationship by visualizations?
:::

Also, there seems that the description of `TWF` in @sec-act1-1-reveal is contradicting our observations.

::: {.callout-caution appearance="simple" collapse="true" icon=false}
:::: {#exr-basics-mv-space}
## Tool wear failure
::::
Identify where the description of `TWF` in @sec-act1-1-reveal does not align with your findings.
:::

