# Process optimization on sensor data via EDA {#sec-act2-eda}
In this section, we will have a look at a more realistic example of industrial data.

## Setting the stage
Imagine a manufacturing chain which is dedicated to produce knifes with wooden handles.
Various machines are interconnected and the process flow is as follows:
- Machine A prepares the steel blade and shaft
- Machine B applies epoxy to the grip area
- Machine C inserts the wooden handle material.
- Machine D is a curing oven, hardening the adhesive.
- Machine E coats the knife with protective finish and completes the manufacturing process.

Operators notice that the process is not running as smoothly as expected.
The handle is not always properly bonded to the metal part and sometimes the wood is cracked.
They find that the root cause of the issue lies in the epoxy application step of machine B.
Common issues include excessive or insufficient epoxy application, uneven distribution, and occasional poor adhesion to the shaft.
One clear economic impact is that these defect products can not be sold.
But there is more to it:
- Waste of material is not sustainable
- The defect actually already happens in Machine B, but Machine C to E still process the faulty products, leading to further waste and costs, especially since the wooden handle is the most expensive part of the product and the curing oven is very energy-intensive.

Since there is a new department focused on data science, they decide to manually inspect the epoxy application right after machine B and label the data accordingly.
Additionally the machine collects some sensor data in a CSV file.
This data set is given to the data science team and in tight collaboration with the operators the ambitious goal is to:
- Optimize the epoxy application process to reduce defects and waste.
- Human inspection is time-consuming and expensive.
Find a way to predict defects occuring in Machine B before the product is handed over to machine C.

Of course, this data science department is us.

## Dataset
The data set consists of sensor readings of a simulated industrial process and consists of two files:

- `simulated_machine_data.csv` stores the sensor data
- `simulated_inspection_data.csv` stores the human inspection results

The sensor data includes the following features in a 200ms resolution:

- `product_id`: Unique identifier for each product.
- `process_step_index`: Index indicating the current step within the process.
                        The machine performs three processing steps: Moving the nozzle to the shaft, applying epoxy, and blow out residual epoxy from nozzle while moving away.
- `timestamp`: Timestamp of the sensor reading.
- `air_temperature_C`: Ambient air temperature in degrees Celsius.
- `process_speed_mm_s`: Set speed of the process in millimeters per second.
- `pressure_measured_bar`: Measured pressure in bar.
- `pressure_setting_bar`: Pressure setting in bar.
- `machine_temperature_C`: Temperature of the machine in degrees Celsius.

The inspection data includes the `product_id` and the `error_code`:

- `product_id`: Unique identifier for each product.
- `error_code`: Code indicating the type of error detected during inspection.

They used `OK` when there was no defect, `NOK_1` (excessive epoxy), `NOK_2` (insufficient epoxy), `NOK_3` (poor adhesion), `NOK_4` (uneven distribution).

## Additional information
The operators state that the epoxy application process is highly sensitive to variations in environmental conditions, such as temperature and humidity.
They believe that incorporating additional sensor data, such as humidity levels, could further enhance understanding of the process.
Also, the pressure settings are critical, since they directly influence the amount of epoxy applied to the product.
The first processing step ensures the correct positioning of the nozzle and the final processing step is supposed to clean the nozzle, preparing it for the next application.



{{< embed /2_act2/3_1_eda.ipynb echo=true >}}

