name: Lint and format check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run ruff lint (check)
        uses: astral-sh/ruff-action@v3
        with:
            args: check

      - name: Run ruff format (check)
        uses: astral-sh/ruff-action@v3
        with:
            args: format --check

