name: Quarto render and publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Lint and format check
        uses: ./.github/workflows/lint_and_format.yml

      - name: Install uv and prepare python environment
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version-file: ".python-version"
          
      - name: Install dependencies
        run: uv sync --locked

      - name: Render document
        run: uv run quarto render --to html
      
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _book
          
